apiVersion: v1
kind: Secret
metadata:
  name: platform-secrets
  namespace: email-platform
type: Opaque
stringData:
  # Relational Database Secret Configurations
  postgres-password: "production-secure-db-password-9931!"
  
  # Object Storage MinIO Credentials
  minio-root-user: "admin-platform-bucket"
  minio-root-password: "super-secure-minio-secret-key-30234!"
  
  # Elasticsearch & Kafka Integration Secrets
  elasticsearch-password: "es-cluster-node-password-50493"
  kafka-scram-password: "kafka-scram-sha512-secure-auth-pwd"
